/* ====== BUILD SYSMAP -- Converts GraphData + InferredConfig to SYSMAP format ======
   Produces {N, E, DT, SUBMAPS} compatible with the 3D renderer (app.js).
   Ported from client/js/loader.js _buildInternalFormat().                   */

import type { GraphData, GraphDataNode } from "@/lib/api";
import type { InferredConfig } from "./engine";

// ── SYSMAP Types ──

export interface SysmapNode {
  id: string;
  label: string;
  sub: string;
  g: string;
  sh: string;
  x: number;
  z: number;
  hero: boolean;
  auto: boolean;
  hidden: boolean;
  _inferredSize: number;
  _properties: Record<string, unknown>;
}

export interface SysmapEdge {
  f: string;
  t: string;
  c: string;
}

export interface DetailTab {
  t: string;
  tp: string;
  d: string;
  m: Record<string, string>;
}

export interface SubmapData {
  title: string;
  nodes: SysmapNode[];
  edges: SysmapEdge[];
}

export interface StatItem {
  label: string;
  value: number;
}

export interface LegendItem {
  label: string;
  color: string;
  edge_type: string;
}

export interface SysmapData {
  N: SysmapNode[];
  E: SysmapEdge[];
  DT: Record<string, DetailTab>;
  SUBMAPS: Record<string, SubmapData>;
  ND: Record<string, unknown>;
  DOC_TREE: unknown[];
  KLIB: Record<string, unknown>;
  title: string;
  description: string;
  stats: StatItem[];
  legend: LegendItem[];
  inferredConfig: InferredConfig;
  graphData: GraphData;
}

// ── Public API ──

export function buildSysmap(
  graphData: GraphData,
  inferred: InferredConfig,
): SysmapData {
  const metadata = graphData.metadata || {};
  const safeNodes = graphData.nodes || [];
  const safeEdges = graphData.edges || [];

  // Build N array
  const N: SysmapNode[] = safeNodes.map((n) => {
    const props = n.properties || {};
    const shape = inferred.shapes.get(n.id) || "sphere";
    const group = n.group || n.type || "module";

    return {
      id: n.id,
      label: n.label || labelFromId(n.id),
      sub: (props.subtitle as string) || (props.description as string) || "",
      g: group,
      sh: shape,
      x: (props.x as number) ?? 0,
      z: (props.z as number) ?? 0,
      hero: (props.hero as boolean) || false,
      auto: (props.auto as boolean) || false,
      hidden: false,
      _inferredSize: inferred.sizes.get(n.id) || 1.0,
      _properties: props as Record<string, unknown>,
    };
  });

  // Build E array
  const E: SysmapEdge[] = safeEdges.map((e) => {
    const edgeProps = e.properties || {};
    return {
      f: e.from,
      t: e.to,
      c: (edgeProps.color as string) || edgeTypeToColor(e.type),
    };
  });

  // Auto-generate DT (detail tabs) from node data
  const DT = autoGenerateDetails(graphData.nodes, E);

  // Auto-generate SUBMAPS from CONTAINS edges
  const SUBMAPS = autoGenerateSubmaps(graphData, N, E, inferred);

  // Title
  const title = metadata.name || "Ontology Cockpit";

  // Stats
  const stats = autoGenerateStats(graphData, N);

  // Legend
  const legend = autoGenerateLegend(E);

  return {
    N,
    E,
    DT,
    SUBMAPS,
    ND: {},
    DOC_TREE: [],
    KLIB: {},
    title,
    description: "",
    stats,
    legend,
    inferredConfig: inferred,
    graphData,
  };
}

// ── Helpers ──

function labelFromId(id: string): string {
  return id
    .replace(/[_.-]/g, " ")
    .replace(/\b\w/g, (c) => c.toUpperCase());
}

function edgeTypeToColor(type?: string): string {
  if (!type) return "white";
  const t = type.toUpperCase();
  if (["HTTP", "GRPC", "REST", "CALLS", "AMQP"].includes(t)) return "cyan";
  if (["CONTAINS", "GROUNDS", "INFORMS"].includes(t)) return "white";
  if (["IMPORTS", "DEPENDS_ON"].includes(t)) return "blue";
  if (["PUBLISHES", "SUBSCRIBES"].includes(t)) return "green";
  if (["DERIVES", "SUPPORTS", "REINFORCES"].includes(t)) return "purple";
  return "white";
}

function autoGenerateStats(
  graphData: GraphData,
  nodes: SysmapNode[],
): StatItem[] {
  const nodeCount = graphData.nodes.length;
  const edgeCount = graphData.edges.length;
  const groups = new Set(nodes.map((n) => n.g));
  const edgeTypes = new Set(
    graphData.edges.map((e) => e.type).filter(Boolean),
  );

  return [
    { label: "Nodes", value: nodeCount },
    { label: "Edges", value: edgeCount },
    { label: "Groups", value: groups.size },
    ...(edgeTypes.size > 0
      ? [{ label: "Edge Types", value: edgeTypes.size }]
      : []),
  ];
}

function autoGenerateLegend(edges: SysmapEdge[]): LegendItem[] {
  const colorLabels: Record<string, string> = {
    green: "Data Flow",
    blue: "Dependencies",
    purple: "Feedback",
    cyan: "Delivery",
    white: "Hierarchy",
  };

  const colorHexes: Record<string, string> = {
    green: "#34d399",
    blue: "#6b8fff",
    purple: "#9b7cff",
    cyan: "#5eead4",
    white: "#8899bb",
  };

  const usedColors = new Set(edges.map((e) => e.c));
  return [...usedColors].map((c) => ({
    label: colorLabels[c] || c,
    color: colorHexes[c] || "#808080",
    edge_type: c,
  }));
}

function autoGenerateDetails(
  nodes: GraphDataNode[],
  edges: SysmapEdge[],
): Record<string, DetailTab> {
  const DT: Record<string, DetailTab> = {};

  // Count edges per node
  const edgeCounts: Record<string, number> = {};
  for (const e of edges) {
    edgeCounts[e.f] = (edgeCounts[e.f] || 0) + 1;
    edgeCounts[e.t] = (edgeCounts[e.t] || 0) + 1;
  }

  for (const n of nodes) {
    const props = n.properties || {};
    const metrics: Record<string, string> = {};

    if (props.loc != null) metrics["LOC"] = String(props.loc);
    if (props.language) metrics["Language"] = String(props.language);
    if (props.complexity != null)
      metrics["Complexity"] = String(props.complexity);
    metrics["Connections"] = String(edgeCounts[n.id] || 0);
    if (props.path) metrics["Path"] = String(props.path);

    DT[n.id] = {
      t: n.label || labelFromId(n.id),
      tp: n.type || "unknown",
      d: (props.description as string) || `${n.type || "Node"}: ${n.label || n.id}`,
      m: metrics,
    };
  }

  return DT;
}

function autoGenerateSubmaps(
  graphData: GraphData,
  sysmapNodes: SysmapNode[],
  sysmapEdges: SysmapEdge[],
  _inferred: InferredConfig,
): Record<string, SubmapData> {
  const SUBMAPS: Record<string, SubmapData> = {};

  // Build parent -> children mapping from CONTAINS edges + parent field
  // Use Set to avoid duplicates from both sources
  const childrenSet: Record<string, Set<string>> = {};
  for (const e of graphData.edges) {
    if (e.type === "CONTAINS") {
      if (!childrenSet[e.from]) childrenSet[e.from] = new Set();
      childrenSet[e.from].add(e.to);
    }
  }
  for (const n of graphData.nodes) {
    if (n.parent) {
      if (!childrenSet[n.parent]) childrenSet[n.parent] = new Set();
      childrenSet[n.parent].add(n.id);
    }
  }

  // Each parent with >2 unique children becomes a submap
  const nodeMap = new Map(sysmapNodes.map((n) => [n.id, n]));

  for (const [parentId, childIdSet] of Object.entries(childrenSet)) {
    const childIds = [...childIdSet];
    if (childIds.length <= 2) continue;

    const parentNode = nodeMap.get(parentId);
    if (!parentNode) continue;

    const submapNodeIds = new Set(childIds);

    // Build submap nodes
    const submapNodes: SysmapNode[] = childIds
      .map((cid) => nodeMap.get(cid))
      .filter((n): n is SysmapNode => n != null);

    // Build submap edges (edges between submap nodes)
    const submapEdges = sysmapEdges.filter(
      (e) => submapNodeIds.has(e.f) && submapNodeIds.has(e.t),
    );

    SUBMAPS[parentId] = {
      title: parentNode.label,
      nodes: submapNodes,
      edges: submapEdges,
    };
  }

  return SUBMAPS;
}
