/**
 * What-If Sandbox — fork the graph for speculative modifications.
 * Pure engine module (no React dependency).
 *
 * Users can drag nodes between modules, create/delete edges,
 * then diff against the original and export as RFC markdown.
 */

import type { Node, Edge } from "@/lib/api";

export interface SandboxState {
  /** Deep-cloned nodes (modifications don't affect original) */
  nodes: Node[];
  /** Deep-cloned edges */
  edges: Edge[];
  /** History of modifications for undo/diff */
  modifications: SandboxModification[];
  /** Whether the sandbox is active */
  active: boolean;
}

export type SandboxModification =
  | { type: "add_edge"; edge: Edge }
  | { type: "remove_edge"; from: string; to: string }
  | { type: "move_node"; nodeId: string; fromParent: string; toParent: string }
  | { type: "add_node"; node: Node }
  | { type: "remove_node"; nodeId: string };

/** Create a sandbox by deep-cloning the current graph */
export function createSandbox(nodes: Node[], edges: Edge[]): SandboxState {
  return {
    nodes: structuredClone(nodes),
    edges: structuredClone(edges),
    modifications: [],
    active: true,
  };
}

/** Add an edge in the sandbox */
export function sandboxAddEdge(
  sandbox: SandboxState,
  from: string,
  to: string,
  edgeType = "RELATES_TO",
): SandboxState {
  const edge: Edge = { from, to, type: edgeType };
  return {
    ...sandbox,
    edges: [...sandbox.edges, edge],
    modifications: [...sandbox.modifications, { type: "add_edge", edge }],
  };
}

/** Remove an edge in the sandbox */
export function sandboxRemoveEdge(
  sandbox: SandboxState,
  from: string,
  to: string,
): SandboxState {
  return {
    ...sandbox,
    edges: sandbox.edges.filter((e) => !(e.from === from && e.to === to)),
    modifications: [
      ...sandbox.modifications,
      { type: "remove_edge", from, to },
    ],
  };
}

/** Compute diff between sandbox and original graph */
export function computeSandboxDiff(
  original: { nodes: Node[]; edges: Edge[] },
  sandbox: SandboxState,
): {
  addedEdges: Edge[];
  removedEdges: Edge[];
  addedNodes: Node[];
  removedNodes: string[];
} {
  const origEdgeSet = new Set(
    original.edges.map((e) => `${e.from}→${e.to}:${e.type}`),
  );
  const sandEdgeSet = new Set(
    sandbox.edges.map((e) => `${e.from}→${e.to}:${e.type}`),
  );
  const origNodeSet = new Set(original.nodes.map((n) => n.id));
  const sandNodeSet = new Set(sandbox.nodes.map((n) => n.id));

  const addedEdges = sandbox.edges.filter(
    (e) => !origEdgeSet.has(`${e.from}→${e.to}:${e.type}`),
  );
  const removedEdges = original.edges.filter(
    (e) => !sandEdgeSet.has(`${e.from}→${e.to}:${e.type}`),
  );
  const addedNodes = sandbox.nodes.filter((n) => !origNodeSet.has(n.id));
  const removedNodes = original.nodes
    .filter((n) => !sandNodeSet.has(n.id))
    .map((n) => n.id);

  return { addedEdges, removedEdges, addedNodes, removedNodes };
}

/** Export sandbox diff as RFC markdown */
export function exportSandboxAsRFC(
  title: string,
  original: { nodes: Node[]; edges: Edge[] },
  sandbox: SandboxState,
): string {
  const diff = computeSandboxDiff(original, sandbox);
  const lines: string[] = [];

  lines.push(`# RFC: ${title}`);
  lines.push("");
  lines.push(`**Generated by**: Ontology Map What-If Sandbox`);
  lines.push(`**Date**: ${new Date().toISOString().split("T")[0]}`);
  lines.push(`**Modifications**: ${sandbox.modifications.length}`);
  lines.push("");

  lines.push("## Proposed Changes");
  lines.push("");

  if (diff.addedEdges.length > 0) {
    lines.push("### New Dependencies");
    for (const e of diff.addedEdges) {
      lines.push(`- \`${e.from}\` → \`${e.to}\` (${e.type})`);
    }
    lines.push("");
  }

  if (diff.removedEdges.length > 0) {
    lines.push("### Removed Dependencies");
    for (const e of diff.removedEdges) {
      lines.push(`- ~~\`${e.from}\` → \`${e.to}\`~~ (${e.type})`);
    }
    lines.push("");
  }

  if (diff.addedNodes.length > 0) {
    lines.push("### New Modules");
    for (const n of diff.addedNodes) {
      lines.push(`- \`${n.id}\` — ${n.text}`);
    }
    lines.push("");
  }

  if (diff.removedNodes.length > 0) {
    lines.push("### Removed Modules");
    for (const id of diff.removedNodes) {
      lines.push(`- ~~\`${id}\`~~`);
    }
    lines.push("");
  }

  lines.push("## Impact Analysis");
  lines.push("");
  lines.push(
    `- **Original**: ${original.nodes.length} nodes, ${original.edges.length} edges`,
  );
  lines.push(
    `- **Proposed**: ${sandbox.nodes.length} nodes, ${sandbox.edges.length} edges`,
  );
  lines.push(
    `- **Net change**: ${diff.addedEdges.length - diff.removedEdges.length} edges, ${diff.addedNodes.length - diff.removedNodes.length} nodes`,
  );

  return lines.join("\n");
}
